CREATE TABLE Users (
id_user INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
country VARCHAR(50) NOT NULL,
address VARCHAR(50) NOT NULL,
usertype VARCHAR(20) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Products(
id_product INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
image_path VARCHAR(100) NOT NULL,
price INT(6) NOT NULL,
brand VARCHAR(50) NOT NULL,
gender VARCHAR(10) NOT NULL,
type VARCHAR(20) NOT NULL,
color VARCHAR(20) NOT NULL,
event VARCHAR(50) NOT NULL,
style VARCHAR(50) NOT NULL,
season VARCHAR(20) NOT NULL,
fabric VARCHAR(1000) NOT NULL,
stock INT(6) NOT NULL,
viewed_by INT(6) NOT NULL DEFAULT 0,
bought_by INT(6) NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Orders(
id_order INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
id_user INT(6) UNSIGNED,
ids_products VARCHAR(100) NOT NULL,
quantities VARCHAR(100) NOT NULL,
total_price INT(6) UNSIGNED NOT NULL,
status VARCHAR(50) NOT NULL,
address VARCHAR(50) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

ALTER TABLE `Orders` ADD CONSTRAINT `fk_user` FOREIGN KEY (`id_user`) REFERENCES `Users`(`id_user`) ON DELETE CASCADE ON UPDATE RESTRICT;
